# Generated by Django 4.2.7 on 2024-04-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='subject',
        ),
        migrations.DeleteModel(
            name='TechCourse',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
